For this activity, you work as a consultant for an airline. The airline is interested in knowing if a better in-flight entertainment experience leads to higher customer satisfaction. They would like you to construct and evaluate a model that predicts whether a future customer would be satisfied with their services given previous customer feedback about their flight experience.

The data for this activity is for a sample size of 129,880 customers. It includes data points such as class, flight distance, and in-flight entertainment, among others. Your goal will be to utilize a binomial logistic regression model to help the airline model and better understand this data.

**Import packages**

Import relevant Python packages. Use train_test_split, LogisticRegression, and various imports from sklearn.metrics to build, visualize, and evalute the model.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

**Load the dataset**
The dataset Invistico_Airline.csv is loaded. The resulting pandas DataFrame is saved as a variable named df_original. As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

In [2]:
# RUN THIS CELL TO IMPORT YOUR DATA.

### YOUR CODE HERE ###
df_original = pd.read_csv("Invistico_Airline.csv")

**Output the first 10 rows**
Output the first 10 rows of data.

In [3]:
df_original.head(10)

satisfaction   Customer Type  Age   Type of Travel     Class  \
0    satisfied  Loyal Customer   65  Personal Travel       Eco   
1    satisfied  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Loyal Customer   70  Personal Travel       Eco   
5    satisfied  Loyal Customer   30  Personal Travel       Eco   
6    satisfied  Loyal Customer   66  Personal Travel       Eco   
7    satisfied  Loyal Customer   10  Personal Travel       Eco   
8    satisfied  Loyal Customer   56  Personal Travel  Business   
9    satisfied  Loyal Customer   22  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   
5             1894             0                                  0   
6              227             0                                  0   
7             1812             0                                  0   
8               73             0                                  0   
9             1556             0                                  0   

   Food and drink  Gate location  ...  Online support  Ease of Online booking  \
0               0              2  ...               2                       3   
1               0              3  ...               2                       3   
2               0              3  ...               2                       2   
3               0              3  ...               3                       1   
4               0              3  ...               4                       2   
5               0              3  ...               2                       2   
6               0              3  ...               5                       5   
7               0              3  ...               2                       2   
8               0              3  ...               5                       4   
9               0              3  ...               2                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   
5                 5                 4                 5                5   
6                 5                 0                 5                5   
7                 3                 3                 4                5   
8                 4                 0                 1                5   
9                 2                 4                 5                3   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   
5            4                2                           0   
6            5                3                          17   
7            4                2                           0   
8            4                4                           0   
9            4                2                          30   

   Arrival Delay in Minutes  
0                       0.0  
1         

**Explore the data**

Check the data type of each column. Note that logistic regression models expect numeric data.

In [4]:
df_original.dtypes

satisfaction                          object
Customer Type                         object
Age                                    int64
Type of Travel                        object
Class                                 object
Flight Distance                        int64
Seat comfort                           int64
Departure/Arrival time convenient      int64
Food and drink                         int64
Gate location                          int64
Inflight wifi service                  int64
Inflight entertainment                 int64
Online support                         int64
Ease of Online booking                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Online boarding                        int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
dtype: obj

**Check the number of satisfied customers in the dataset**

To predict customer satisfaction, check how many customers in the dataset are satisfied before modeling.

In [5]:
df_original['satisfaction'].value_counts()

satisfaction
satisfied       71087
dissatisfied    58793
Name: count, dtype: int64

**Check for missing values**

An assumption of logistic regression models is that there are no missing values. Check for missing values in the rows of the data.

In [6]:
df_original.isnull().sum()

satisfaction                           0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Seat comfort                           0
Departure/Arrival time convenient      0
Food and drink                         0
Gate location                          0
Inflight wifi service                  0
Inflight entertainment                 0
Online support                         0
Ease of Online booking                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Online boarding                        0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
dtype: int64

**Drop the rows with missing values**

Drop the rows with missing values and save the resulting pandas DataFrame in a variable named df_subset.

In [7]:
df_subset = df_original.dropna()

**Prepare the data**



Make the Inflight entertainment column "of type float."

In [8]:
df_subset['Inflight entertainment'] = df_subset['Inflight entertainment'].astype(float)

C:\Users\miche\AppData\Local\Temp\ipykernel_5704\1134931839.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['Inflight entertainment'] = df_subset['Inflight entertainment'].astype(float)


**Convert the categorical column satisfaction into numeric**

Convert the categorical column satisfaction into numeric through one-hot encoding.

In [9]:
df_subset = pd.get_dummies(df_subset, columns=['satisfaction'], drop_first=False)

**Output the first 10 rows of df_subset**

To examine what one-hot encoding did to the DataFrame, output the first 10 rows of df_subset.

In [10]:
df_subset.head(10)

Customer Type  Age   Type of Travel     Class  Flight Distance  \
0  Loyal Customer   65  Personal Travel       Eco              265   
1  Loyal Customer   47  Personal Travel  Business             2464   
2  Loyal Customer   15  Personal Travel       Eco             2138   
3  Loyal Customer   60  Personal Travel       Eco              623   
4  Loyal Customer   70  Personal Travel       Eco              354   
5  Loyal Customer   30  Personal Travel       Eco             1894   
6  Loyal Customer   66  Personal Travel       Eco              227   
7  Loyal Customer   10  Personal Travel       Eco             1812   
8  Loyal Customer   56  Personal Travel  Business               73   
9  Loyal Customer   22  Personal Travel       Eco             1556   

   Seat comfort  Departure/Arrival time convenient  Food and drink  \
0             0                                  0               0   
1             0                                  0               0   
2             0                                  0               0   
3             0                                  0               0   
4             0                                  0               0   
5             0                                  0               0   
6             0                                  0               0   
7             0                                  0               0   
8             0                                  0               0   
9             0                                  0               0   

   Gate location  Inflight wifi service  ...  On-board service  \
0              2                      2  ...                 3   
1              3                      0  ...                 4   
2              3                      2  ...                 3   
3              3                      3  ...                 1   
4              3                      4  ...                 2   
5              3                      2  ...                 5   
6              3                      2  ...                 5   
7              3                      2  ...                 3   
8              3                      5  ...                 4   
9              3                      2  ...                 2   

   Leg room service  Baggage handling  Checkin service  Cleanliness  \
0                 0                 3                5            3   
1                 4                 4                2            3   
2                 3                 4                4            4   
3                 0                 1                4            1   
4                 0                 2                4            2   
5                 4                 5                5            4   
6                 0                 5                5            5   
7                 3                 4                5            4   
8                 0                 1                5            4   
9                 4                 5                3            4   

   Online boarding  Departure Delay in Minutes  Arrival Delay in Minutes  \
0                2                           0                       0.0   
1                2                         310                     305.0   
2                2                           0                       0.0   
3                3                           0                       0.0   
4                5                           0                       0.0   
5                2                           0                       0.0   
6                3                          17                      15.0   
7                2                           0                       0.0   
8                4                           0                       0.0   
9                2                          30                      26.0   

   satisfaction_dissatisfied  satisfaction_satisfied  
0                      False                    True  
1     

**Create the training and testing data**

Put 70% of the data into a training set and the remaining 30% into a testing set. Create an X and y DataFrame with only the necessary variables.

In [11]:
X = df_subset[['Inflight entertainment']]
y = df_subset['satisfaction_satisfied']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

**Fit a LogisticRegression model to the data**

Build a logistic regression model and fit the model to the training data.

In [12]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

**Obtain parameter estimates**

Make sure you output the two parameters from your model.

In [13]:
model.coef_

array([[0.99752883]])

In [14]:
model.intercept_

array([-3.19359054])

**Predict the outcome for the test dataset**

Now that you've completed your regression, review and analyze your results. First, input the holdout dataset into the predict function to get the predicted labels from the model. Save these predictions as a variable called y_pred.

In [15]:
y_pred = model.predict(X_test)

**Print out y_pred** 

In order to examine the predictions, print out y_pred.

In [16]:
print(y_pred)

[ True False False ... False False False]


Use the predict_proba and predict functions on X_test¶

In [17]:
y_pred_proba = model.predict_proba(X_test)
print(y_pred_proba)

[[0.14257646 0.85742354]
 [0.55008251 0.44991749]
 [0.89989529 0.10010471]
 ...
 [0.89989529 0.10010471]
 [0.76826369 0.23173631]
 [0.55008251 0.44991749]]


***Analyze the results***

Print out the model's accuracy, precision, recall, and F1 score.

In [18]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Accuracy: 0.8015290756042938
Precision: 0.8161420273561926
Recall: 0.8215296114673708
F1 Score: 0.8188269574208102


**Produce a confusion matrix**

Data professionals often like to know the types of errors made by an algorithm. To obtain this information, produce a confusion matrix.

In [19]:
confusion_matrix(y_test, y_pred)

array([[13714,  3925],
       [ 3785, 17423]])